Repository daita-technologies/daita-python-library, pull requests merged in 2022-11, with the labels that each got.

#11 Feat: Show progress bar for uploads
  CHANGELOG.md
  daita/.env.development
  daita/upload_zip.py
Labels: feature 💥

#10 Feat: Handling of unexpected interruptions during upload
  CHANGELOG.md
  daita/daita.py
  daita/dashboard.py
  daita/upload_images.py
Labels: feature 💥

#8 Feat: Remove `.env.development` file
  .github/workflows/build.yml
  .github/workflows/publish-pypi.yml
  .github/workflows/publish-test-pypi.yml
  .gitignore
  CHANGELOG.md
  daita/.env.development
  daita/load_env.py
Labels: feature 💥

#9 Release version `0.0.7`.
  .github/workflows/build.yml
  .github/workflows/publish-pypi.yml
  .github/workflows/publish-test-pypi.yml
  .gitignore
  CHANGELOG.md
  daita/.env.development
  daita/__init__.py
  daita/daita.py
  daita/dashboard.py
  daita/load_env.py
  daita/upload_images.py
  daita/upload_zip.py
  daita/utils.py
  setup.py
Labels: bug 🐛, feature 💥

#12 ✨ Release 0.0.7 `daita-python-library`
  .github/workflows/build.yml
  .github/workflows/publish-pypi.yml
  .github/workflows/publish-test-pypi.yml
  .gitignore
  CHANGELOG.md
  daita/.env.development
  daita/__init__.py
  daita/daita.py
  daita/dashboard.py
  daita/load_env.py
  daita/upload_images.py
  daita/upload_zip.py
  daita/utils.py
  setup.py
Labels: feature 💥, frontend 🖥, python 🐍, refactor 🛠

#16 ♻️ fix env variable naming
  .github/workflows/build.yml
  .github/workflows/publish-pypi.yml
  .github/workflows/publish-test-pypi.yml
  daita/__init__.py
  daita/upload_zip.py
Labels: bug 🐛
